title: Test Page
author: michelsoliveira
email: michel.s.oliveira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  thsi site is a test to create git hub pages!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
